version: '3'

services:
  usertoserver:
    build: .
    volumes:
      - shared_data:/app/data
    command: python -u /app/userToServer.py
    network_mode: "host"

  servertouser:
    build: .
    volumes:
      - shared_data:/app/data
    command: sh -c "./checkplugin.sh"
    network_mode: "host"

volumes:
  shared_data: